//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTips.Spargine.Tester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetTips.Spargine.Tester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CountryData {
            get {
                object obj = ResourceManager.GetObject("CountryData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa,aarp,abarth,abb,abbott,abbvie,abc,able,abogado,abudhabi,ac,academy,accenture,accountant,accountants,aco,active,actor,ad,adac,ads,adult,ae,aeg,aero,aetna,af,afamilycompany,afl,africa,ag,agakhan,agency,ai,aig,aigo,airbus,airforce,airtel,akdn,al,alfaromeo,alibaba,alipay,allfinanz,allstate,ally,alsace,alstom,am,amazon,americanexpress,americanfamily,amex,amfam,amica,amsterdam,an,analytics,android,anquan,anz,ao,aol,apartments,app,apple,aq,aquarelle,ar,arab,aramco,archi,army,arpa,art,arte,as,asda,asia,associat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DomainExtentions {
            get {
                return ResourceManager.GetString("DomainExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address length is limited to 100 characters..
        /// </summary>
        internal static string ErrorAddressLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorAddressLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City length is limited to 100 characters..
        /// </summary>
        internal static string ErrorCityLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorCityLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country length is limited to 55 characters..
        /// </summary>
        internal static string ErrorCountryLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorCountryLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County/ Province length is limited to 60 characters..
        /// </summary>
        internal static string ErrorCountyProvinceLengthIsLimitedToCharacter {
            get {
                return ResourceManager.GetString("ErrorCountyProvinceLengthIsLimitedToCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date text is null or empty..
        /// </summary>
        internal static string ErrorDateTextIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorDateTextIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name length is limited to 50 characters..
        /// </summary>
        internal static string ErrorFirstNameLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorFirstNameLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id length is limited to 50 characters..
        /// </summary>
        internal static string ErrorIdLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorIdLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format..
        /// </summary>
        internal static string ErrorInvalidDateFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON value is null or not a valid TimeOnly representation..
        /// </summary>
        internal static string ErrorJSONValueIsNullOrNotAValidTimeOnlyRepresentation {
            get {
                return ResourceManager.GetString("ErrorJSONValueIsNullOrNotAValidTimeOnlyRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name length is limited to 50 characters..
        /// </summary>
        internal static string ErrorLastNameLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorLastNameLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person BornOn cannot be in the future..
        /// </summary>
        internal static string ErrorMessageBornOnCannotBeInTheFuture {
            get {
                return ResourceManager.GetString("ErrorMessageBornOnCannotBeInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email length is limited required to be 10 to 75 characters..
        /// </summary>
        internal static string ErrorMessageEmailLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorMessageEmailLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is limited to 50 characters..
        /// </summary>
        internal static string ErrorMessagePhoneNumberIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorMessagePhoneNumberIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code length is limited to 25 characters..
        /// </summary>
        internal static string ErrorPostalCodeLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorPostalCodeLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State length is limited to 60 characters..
        /// </summary>
        internal static string ErrorStateLengthIsLimitedToCharacters {
            get {
                return ResourceManager.GetString("ErrorStateLengthIsLimitedToCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supported by {1}..
        /// </summary>
        internal static string ErrorTypeNotSupportedByMethod {
            get {
                return ResourceManager.GetString("ErrorTypeNotSupportedByMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize countries data..
        /// </summary>
        internal static string FailedToDeserializeCountriesData {
            get {
                return ResourceManager.GetString("FailedToDeserializeCountriesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron,Abbie,Abby,Abel,Abigail,Abraham,Ada,Adam,Adan,Addie,Adela,Adelaide,Adele,Adeline,Adolfo,Adolph,Adrian,Adrian,Adriana,Adrienne,Agnes,Agustin,Aida,Aileen,Aimee,Aisha,Al,Alan,Alana,Alba,Albert,Alberta,Alberto,Alejandra,Alejandro,Alex,Alexander,Alexandra,Alexandria,Alexis,Alexis,Alfonso,Alfred,Alfreda,Alfredo,Ali,Alice,Alicia,Aline,Alisa,Alisha,Alison,Alissa,Allan,Allen,Allene,Allie,Allison,Allyson,Alma,Alonzo,Alphonso,Alta,Althea,Alton,Alvaro,Alvin,Alyce,Alyson,Alyssa,Amalia,Amanda,Amber,Amelia,Amie,Amos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbott,Abel,Abraham,Abrams,Acevedo,Ackerman,Acosta,Adair,Adams,Adkins,Aguilar,Aguilera,Aguirre,Ahmed,Akers,Akins,Albert,Albrecht,Albright,Aldrich,Aldridge,Alexander,Alfaro,Alford,Ali,Allen,Allison,Allred,Alonso,Alston,Alvarado,Alvarez,Amaya,Ambrose,Ames,Amos,Anaya,Andersen,Anderson,Andrade,Andrews,Angel,Anthony,Aquino,Aragon,Archer,Arellano,Arias,Armstrong,Arnold,Arredondo,Arrington,Arroyo,Arthur,Ash,Ashby,Ashley,Atkins,Atkinson,Atwood,Austin,Avalos,Avery,Avila,Aviles,Ayala,Ayers,Babcock,Baca,Bacon,Baez,Bag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing and formatting are the lifeblood of any modern web app or service: take data off the wire, parse it, manipulate it, format it back out. As such, in .NET Core 2.1 along with bringing up Span&lt;T&gt;, we invested in the formatting and parsing of primitives, from Int32 to DateTime. Many of those changes can be read about in my previous blog posts, but one of the key factors in enabling those performance improvements was in moving a lot of native code to managed. That may be counter-intuitive, in that it’s “ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongTestString {
            get {
                return ResourceManager.GetString("LongTestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a Coordinate..
        /// </summary>
        internal static string ObjectIsNotACoordinate {
            get {
                return ResourceManager.GetString("ObjectIsNotACoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a {1} type..
        /// </summary>
        internal static string ObjectIsNotType {
            get {
                return ResourceManager.GetString("ObjectIsNotType", resourceCulture);
            }
        }
    }
}
