<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<AnalysisLevel>latest-recommended</AnalysisLevel>
	<AnalysisMode>AllEnabledByDefault</AnalysisMode>
	<ApplicationIcon>SPARGINE-ICON-GRAPHIC-SMALL.ico</ApplicationIcon>
	<AssemblyName>$(MSBuildProjectName)</AssemblyName>
	<AssemblyVersion>2025.12.12.1</AssemblyVersion>
	<Authors>David McCarter</Authors>
	<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
	<AutoIncrementPackageRevision>true</AutoIncrementPackageRevision>
	<BaseOutputPath>..\..\AppBin</BaseOutputPath>
	<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
	<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
	<Company>dotNetTips.com - McCarter Consulting</Company>
	<Configurations>Debug;Release</Configurations>
	<Copyright>McCarter Consulting (David McCarter)</Copyright>
	<DebugSymbols>true</DebugSymbols>
	<DebugType>portable</DebugType>
	<Description>Core types and helper methods for Spargine.</Description>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
	<EnableNETAnalyzers>true</EnableNETAnalyzers>
	<EnablePackageValidation>false</EnablePackageValidation>
	<EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	<FileVersion>2025.12.12.1</FileVersion>
	<GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>
	<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	<ImplicitUsings>enable</ImplicitUsings>
	<IncludeSymbols>true</IncludeSymbols>
	<LangVersion>latest</LangVersion>
	<NeutralLanguage>en-US</NeutralLanguage>
	<Nullable>enable</Nullable>
	<PackageIcon>SPARGINE-ICON-GRAPHIC-SMALL.png</PackageIcon>
	<PackageProjectUrl>https://github.com/RealDotNetDave/DotNetTips.Spargine.10</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	<PackageTags>David McCarter, dotNetDave, dotNetTips.com, Spargine</PackageTags>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/RealDotNetDave/DotNetTips.Spargine.10</RepositoryUrl>
	<RootNamespace>DotNetTips.Spargine.Core</RootNamespace>
	<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
	<RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
	<ServerGarbageCollection>true</ServerGarbageCollection>
	<SignAssembly>false</SignAssembly>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<TargetFramework>net10.0</TargetFramework>
	<Title>DotNetTips.Spargine.10.Core</Title>
	<Version>2025.12.12.1</Version>
  </PropertyGroup>

  <PropertyGroup>
	<NuGetAudit>true</NuGetAudit>
	<NuGetAuditMode>all</NuGetAuditMode>
	<NuGetAuditLevel>low</NuGetAuditLevel>
	<WarningsAsErrors Condition="$(ContinuousIntegrationBuild) == 'true' OR '$(Configuration)' == 'Release'">(WarningsAsErrors);NU1900;NU1901;NU1902;NU1903;NU1904</WarningsAsErrors>
	<PackageReleaseNotes>--JAN 2026: Initial .NET 10 release.</PackageReleaseNotes>
	<PackAsTool>False</PackAsTool>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<OutputPath>..\..\AppBin\</OutputPath>
	<DocumentationFile>..\..\AppBin\dotNetTips.Spargine.10.Core.xml</DocumentationFile>
	<WarningLevel>9999</WarningLevel>
	<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
	<Optimize>false</Optimize>
	<NoWarn />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<OutputPath>..\..\AppBin\</OutputPath>
	<DocumentationFile>..\..\AppBin\dotNetTips.Spargine.10.Core.xml</DocumentationFile>
	<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
	<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	<WarningLevel>9999</WarningLevel>
	<Optimize>true</Optimize>
	<NoWarn />
  </PropertyGroup>

  <ItemGroup>
	<Compile Remove="IEasyDisposable.cs" />
	<Compile Remove="Security\BarCode.cs" />
  </ItemGroup>

  <ItemGroup>
	<Content Include="SPARGINE-ICON-GRAPHIC-SMALL.ico" />
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Include="SPARGINE-ICON-GRAPHIC-SMALL.png">
	  <Pack>true</Pack>
	  <PackagePath>\</PackagePath>
	  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	</EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
	<None Include="..\..\README.md">
	  <Pack>true</Pack>
	  <PackagePath>\</PackagePath>
	</None>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
	<PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
	<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
	<PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="4.14.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.1" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
	<PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.1" />
	<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
	<PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>

  <ItemGroup>
	<Compile Update="Properties\Resources.Designer.cs">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Resources.resx</DependentUpon>
	</Compile>
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Update="Properties\Resources.resx">
	  <Generator>ResXFileCodeGenerator</Generator>
	  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	</EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
	<Folder Include="Data\Models\" />
  </ItemGroup>

</Project>
