//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTips.Spargine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetTips.Spargine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly company name attribute is not set..
        /// </summary>
        internal static string AssemblyCompanyNameAttributeIsNotSet {
            get {
                return ResourceManager.GetString("AssemblyCompanyNameAttributeIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create directory..
        /// </summary>
        internal static string CouldNotCreateDirectory {
            get {
                return ResourceManager.GetString("CouldNotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted folder..
        /// </summary>
        internal static string DeletedFolder {
            get {
                return ResourceManager.GetString("DeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path in zip archive..
        /// </summary>
        internal static string ErrorInvalidFilePathZipArchive {
            get {
                return ResourceManager.GetString("ErrorInvalidFilePathZipArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create temporary file..
        /// </summary>
        internal static string FailedToCreateTemporaryFile {
            get {
                return ResourceManager.GetString("FailedToCreateTemporaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been copied..
        /// </summary>
        internal static string FileHasBeenCopied {
            get {
                return ResourceManager.GetString("FileHasBeenCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been deleted..
        /// </summary>
        internal static string FileHasBeenDeleted {
            get {
                return ResourceManager.GetString("FileHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been moved..
        /// </summary>
        internal static string FileHasBeenMoved {
            get {
                return ResourceManager.GetString("FileHasBeenMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found..
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process {0} has been killed on {1}..
        /// </summary>
        internal static string ProcessHasBeenKilled {
            get {
                return ResourceManager.GetString("ProcessHasBeenKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} was not found..
        /// </summary>
        internal static string ResourceWasNotFound {
            get {
                return ResourceManager.GetString("ResourceWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retries are limited to 1 - 255..
        /// </summary>
        internal static string RetriesAreLimitedTo255 {
            get {
                return ResourceManager.GetString("RetriesAreLimitedTo255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} has been started on {1}..
        /// </summary>
        internal static string ServiceHasBeenStartedOn {
            get {
                return ResourceManager.GetString("ServiceHasBeenStartedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} has been stopped on {1}..
        /// </summary>
        internal static string ServiceHasBeenStoppedOn {
            get {
                return ResourceManager.GetString("ServiceHasBeenStoppedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found..
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory for the file cannot be the same as the destination..
        /// </summary>
        internal static string TheDirectoryForTheFileCannotBeTheSameAsThe {
            get {
                return ResourceManager.GetString("TheDirectoryForTheFileCannotBeTheSameAsThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been canceled..
        /// </summary>
        internal static string TheOperationHasBeenCanceled {
            get {
                return ResourceManager.GetString("TheOperationHasBeenCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has timed out..
        /// </summary>
        internal static string TheOperationHasTimedOut {
            get {
                return ResourceManager.GetString("TheOperationHasTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root directory of the file is null..
        /// </summary>
        internal static string TheRootDirectoryOfTheFileIsNull {
            get {
                return ResourceManager.GetString("TheRootDirectoryOfTheFileIsNull", resourceCulture);
            }
        }
    }
}
