<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AnalysisLevel>none</AnalysisLevel>
    <AssemblyVersion>2026.10.4.17</AssemblyVersion>
    <BaseOutputPath>..\..\..\AppBin</BaseOutputPath>
    <Company>dotNetTips.com - McCarter Consulting</Company>
    <Configurations>Debug;Release</Configurations>
    <Copyright>McCarter Consulting (David McCarter)</Copyright>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <FileVersion>2026.10.4.17</FileVersion>
	    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
	<Nullable>enable</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <TargetFramework>net10.0</TargetFramework>
    <Version>2026.10.4.17</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\AppBin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\AppBin</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Data\CountriesTests.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.8" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\dotNetTips.Spargine.10.Core\DotNetTips.Spargine.10.Core.csproj" />
    <ProjectReference Include="..\..\dotNetTips.Spargine.10.Extensions\DotNetTips.Spargine.10.Extensions.csproj" />
    <ProjectReference Include="..\..\dotNetTips.Spargine.10.Tester\DotNetTips.Spargine.10.Tester.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
