<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<AnalysisLevel>none</AnalysisLevel>
	<AssemblyVersion>2024.8.3.1</AssemblyVersion>
	<BaseOutputPath>..\..\..\AppBin</BaseOutputPath>
	<EnableNETAnalyzers>false</EnableNETAnalyzers>
	<FileVersion>2025.8.5.1</FileVersion>
	<IsPackable>false</IsPackable>
	<NeutralLanguage>en-US</NeutralLanguage>
	<RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
	<RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
	<TargetFramework>net10.0-windows</TargetFramework>
	<Version>2024.8.3.1</Version>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
	<Compile Remove="IO\FilePropertyReaderWriterTests.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
	<PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
	<PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\dotNetTips.Spargine.10.Extensions\dotNetTips.Spargine.10.Extensions.csproj" />
	<ProjectReference Include="..\..\dotNetTips.Spargine.10.Tester\dotNetTips.Spargine.10.Tester.csproj" />
	<ProjectReference Include="..\..\dotNetTips.Spargine.10\DotNetTips.Spargine.10.csproj" />
  </ItemGroup>

</Project>
