// ***********************************************************************
// Assembly         : DotNetTips.Spargine.10.Extensions
// Author           : David McCarter
// Created          : 11-21-2020
//
// Last Modified By : Copilot Agent
// Last Modified On : 05-21-2026
// ***********************************************************************
// <copyright file="DictionaryExtensions.cs" company="dotNetTips.com - McCarter Consulting">
//     Copyright (c) David McCarter - dotNetTips.com. All rights reserved.
// </copyright>
// <summary>
// Extension methods for <see cref="System.Collections.Generic.IDictionary{TKey, TValue}"/> providing
// add, update, query, and conversion utilities. Includes <c>AddIfNotExists</c>, <c>AddRange</c>,
// <c>DisposeCollection</c>, <c>GetOrAdd</c>, <c>IsNotEmpty</c>, <c>ToConcurrentDictionary</c>,
// <c>ToDelimitedString</c>, <c>ToFrozen</c>, <c>ToImmutable</c>, <c>ToImmutableSorted</c>,
// <c>ToLookupWithDefault</c>, <c>ToReadOnly</c>, <c>ToSorted</c>, <c>TryGetValue</c>, and
// <c>Upsert</c>. Obsolete variants are preserved with deprecation notices pointing to replacements.
// </summary>
// ***********************************************************************
using System.Collections.Concurrent;
using System.Collections.Frozen;
using System.Collections.Immutable;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Diagnostics.Contracts;
using System.Runtime.CompilerServices;
using DotNetTips.Spargine.Core;

//'![](7050BB9CE02F97B17501B57A581147A7.png;https://bit.ly/Spargine ;;0.01188,0.01188)

namespace DotNetTips.Spargine.Extensions;

/// <summary>
/// Provides extension methods for <see cref="IDictionary{TKey, TValue}"/> that enhance dictionary functionality
/// with add, update, query, disposal, and conversion operations.
/// <para>Key capabilities include:</para>
/// <list type="bullet">
/// <item><description><b>Add/Update:</b> <c>AddIfNotExists</c>, <c>AddRange</c>, <c>Upsert</c></description></item>
/// <item><description><b>Query:</b> <c>GetOrAdd</c>, <c>IsNotEmpty</c>, <c>TryGetValue</c>, <c>ToLookupWithDefault</c></description></item>
/// <item><description><b>Disposal:</b> <c>DisposeCollection</c></description></item>
/// <item><description><b>Conversion:</b> <c>ToConcurrentDictionary</c>, <c>ToDelimitedString</c>, <c>ToFrozen</c>,
/// <c>ToImmutable</c>, <c>ToImmutableSorted</c>, <c>ToReadOnly</c>, <c>ToSorted</c></description></item>
/// </list>
/// Obsolete methods are retained with deprecation notices that redirect to their modern replacements.
/// </summary>
[Information(Status = Status.Available, Documentation = "https://bit.ly/SpargineDictionaryExtensions")]
public static class DictionaryExtensions
{
	/// <summary>
	/// Adds the specified key and value to the dictionary if the key does not already exist.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to add to.</param>
	/// <param name="key">The key of the element to add.</param>
	/// <param name="value">The value of the element to add. It must not be null.</param>
	/// <returns>true if the key/value pair was added to the dictionary successfully; otherwise, false.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection" />, <paramref name="key" />, or <paramref name="value" /> is null.</exception>
	[Information("From .NET Core source.", author: "David McCarter", createdOn: "7/15/2020", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static bool AddIfNotExists<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [DisallowNull] TKey key, [AllowNull] in TValue value)
		where TKey : notnull
		where TValue : notnull
	{
		if (value is null)
		{
			return false;
		}

		key = key.ArgumentNotNull();

		return collection.TryAdd(key, value);
	}


	/// <summary>
	/// Adds a range of key/value pairs to the dictionary. Each item from the specified collection is added to the dictionary
	/// if the key generated by the key selector does not already exist in the dictionary.
	/// </summary>
	/// <typeparam name="T">The type of the items in the collection.</typeparam>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to add the items to.</param>
	/// <param name="items">The collection of items to add to the dictionary.</param>
	/// <param name="keyFunction">A function to extract the key from each item.</param>
	/// <param name="valueFunction">A function to extract the value from each item.</param>
	/// <returns><c>true</c> if at least one item was added to the dictionary; otherwise, <c>false</c>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/>, <paramref name="items"/>, <paramref name="keyFunction"/>, or <paramref name="valueFunction"/> is null.</exception>
	[DebuggerStepThrough]
	[Information(nameof(AddRange), "David McCarter", "11/21/2020", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static bool AddRange<T, TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [DisallowNull] IEnumerable<T> items, [DisallowNull] Func<T, TKey> keyFunction, Func<T, TValue> valueFunction)
		where TKey : notnull
		where TValue : notnull
	{
		if (valueFunction is null)
		{
			return false;
		}

		if (items.CheckItemsExists() is false)
		{
			return false;
		}

		keyFunction = keyFunction.ArgumentNotNull();
		collection = collection.ArgumentNotNull();

		var added = false;

		foreach (var item in items)
		{
			var itemKey = keyFunction(item);
			var itemValue = valueFunction(item);

			// TryAdd returns true if added, false if key exists
			if (collection.TryAdd(itemKey, itemValue))
			{
				added = true;
			}
		}

		return added;
	}

	/// <summary>
	/// Disposes of all disposable items within the dictionary. Each item in the dictionary that implements <see cref="IDisposable"/> will be disposed.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary, which must implement <see cref="IDisposable"/> if they are to be disposed.</typeparam>
	/// <param name="collection">The dictionary containing the items to dispose.</param>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is null.</exception>
	[Information(nameof(DisposeCollection), "David McCarter", "11/21/2020", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.NotRequired, Status = Status.Available)]
	public static void DisposeCollection<TKey, TValue>([DisallowNull] this IEnumerable<KeyValuePair<object, IDisposable>> collection) where TKey : notnull
		where TValue : notnull
	{
		var items = collection.Select(p => p.Value);

		if (items.IsNotEmpty())
		{
			foreach (var item in items)
			{
				if (item is IDisposable disposeItem)
				{
					disposeItem.TryDispose();
				}
			}
		}
	}

	/// <summary>
	/// Gets the value associated with the specified key or adds it if the key does not exist.
	/// </summary>
	/// <typeparam name="TKey">The type of keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to search or add to.</param>
	/// <param name="key">The key of the value to get or add.</param>
	/// <param name="value">The value to add if the key does not exist.</param>
	/// <returns>The value associated with the specified key. This will be either the existing value for the key if the key is already in the dictionary, or the new value if the key was not in the dictionary.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection" />, <paramref name="key" />, or <paramref name="value" /> is null.</exception>
	/// <remarks>
	/// <para>
	/// This method provides a "get-or-add" operation that retrieves an existing value or adds a new one.
	/// </para>
	/// <para>
	/// <b>Performance Optimization:</b> Uses <see cref="IDictionary{TKey, TValue}.TryGetValue"/> followed by 
	/// <see cref="IDictionary{TKey, TValue}.Add"/> when the key doesn't exist. This approach uses two O(1) operations: 
	/// one to check for the key's existence and another to add it if absent. The <c>TryGetValue</c> method is the 
	/// most efficient way to check for key existence in .NET 10 dictionaries.
	/// </para>
	/// <para>
	/// <b>Thread Safety:</b> This method is not atomic for regular <see cref="Dictionary{TKey, TValue}"/>. 
	/// For thread-safe operations, use <see cref="ConcurrentDictionary{TKey, TValue}.GetOrAdd(TKey, TValue)"/> instead.
	/// </para>
	/// <para>
	/// <b>Comparison to ConcurrentDictionary:</b>
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <description>
	/// This extension mimics <see cref="ConcurrentDictionary{TKey, TValue}.GetOrAdd(TKey, TValue)"/> 
	/// behavior for regular dictionaries.
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// Unlike <c>ConcurrentDictionary.GetOrAdd</c>, this is not thread-safe - use appropriate 
	/// synchronization if called from multiple threads.
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// For concurrent scenarios, <see cref="ConcurrentDictionary{TKey, TValue}.GetOrAdd(TKey, TValue)"/> 
	/// is optimized with fine-grained locking and lock-free read operations.
	/// </description>
	/// </item>
	/// </list>
	/// </remarks>
	/// <example>
	/// <code>
	/// var cache = new Dictionary&lt;string, ExpensiveObject&gt;();
	/// 
	/// // Get existing value or add new one
	/// var obj = cache.GetOrAdd("key1", new ExpensiveObject());
	/// 
	/// // Second call returns the cached instance
	/// var sameObj = cache.GetOrAdd("key1", new ExpensiveObject()); // obj == sameObj
	/// </code>
	/// </example>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(GetOrAdd), author: "David McCarter", createdOn: "7/15/2020", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static TValue GetOrAdd<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [DisallowNull] TKey key, [DisallowNull] TValue value)
	where TKey : notnull
	where TValue : notnull
	{
		value = value.ArgumentNotNull();
		key = key.ArgumentNotNull();
		collection = collection.ArgumentNotNull();

		if (collection.TryGetValue(key, out var item) is false)
		{
			collection.Add(key, value);
			item = value;
		}

		return item;
	}

	/// <summary>
	/// Determines whether the dictionary has any items that match the specified condition.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to test.</param>
	/// <param name="actionPredicate">A function that tests each key/value pair for a condition.</param>
	/// <returns><c>true</c> if at least one key/value pair satisfies <paramref name="actionPredicate"/>; otherwise, <c>false</c>.</returns>
	[Pure]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(IsNotEmpty), author: "David McCarter", createdOn: "6/15/2022", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static bool IsNotEmpty<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, Func<KeyValuePair<TKey, TValue>, bool> actionPredicate)
	{
		return collection is not null && actionPredicate is not null && collection.Any(actionPredicate);
	}

	/// <summary>
	/// Creates a <see cref="ConcurrentDictionary{TKey, TValue}"/> from an existing <see cref="IDictionary{TKey, TValue}"/>.
	/// </summary>
	/// <typeparam name="TKey">The type of keys in the dictionary. Must be non-nullable.</typeparam>
	/// <typeparam name="TValue">The type of values in the dictionary.</typeparam>
	/// <param name="collection">The source dictionary to copy into a concurrent dictionary. Must not be <c>null</c>.</param>
	/// <param name="comparer">
	/// An optional <see cref="IEqualityComparer{T}"/> to use for key comparison.
	/// If <c>null</c>, <see cref="EqualityComparer{T}.Default"/> is used.
	/// </param>
	/// <returns>
	/// A new <see cref="ConcurrentDictionary{TKey, TValue}"/> containing all key/value pairs from <paramref name="collection"/>.
	/// </returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is <c>null</c>.</exception>
	/// <remarks>
	/// This method creates a new concurrent dictionary and copies the contents of the source dictionary.
	/// The resulting collection is safe for concurrent read/write operations, but the original
	/// <paramref name="collection"/> remains unchanged and is not synchronized with the new instance.
	/// </remarks>
	/// <example>
	/// <code>
	/// var dict = new Dictionary&lt;string, int&gt; { ["one"] = 1, ["two"] = 2 };
	/// ConcurrentDictionary&lt;string, int&gt; concurrent = dict.ToConcurrentDictionary();
	/// 
	/// concurrent.TryAdd("three", 3);
	/// // dict is unchanged; concurrent now has 3 entries.
	/// </code>
	/// </example>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToConcurrentDictionary), "David McCarter", "7/23/2022", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static ConcurrentDictionary<TKey, TValue> ToConcurrentDictionary<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, IEqualityComparer<TKey>? comparer = null) where TKey : notnull
	{
		return new ConcurrentDictionary<TKey, TValue>(collection.ArgumentNotNull(), comparer ?? EqualityComparer<TKey>.Default);
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}" /> to a delimited string using <c>FastStringBuilder</c> for performance.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to convert.</param>
	/// <param name="delimiter">The delimiter character to use between entries.</param>
	/// <returns>A <see cref="string"/> where each key/value pair is separated by <paramref name="delimiter"/>.</returns>
	[Pure]
	[return: NotNull]
	[Information(nameof(ToDelimitedString), "David McCarter", "11/03/2020", "11/21/2020", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static string ToDelimitedString<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [ConstantExpected] char delimiter = ControlChars.Comma) where TKey : notnull
	{
		return FastStringBuilder.ToDelimitedString((Dictionary<TKey, TValue>)collection, delimiter);
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}"/> to a <see cref="FrozenDictionary{TKey, TValue}"/>,
	/// an immutable dictionary optimized for fast read operations.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="list">The source dictionary to convert.</param>
	/// <param name="comparer">
	/// An optional <see cref="IEqualityComparer{T}"/> to use for key comparison.
	/// If <c>null</c>, <see cref="EqualityComparer{T}.Default"/> is used.
	/// </param>
	/// <returns>A frozen dictionary containing all key-value pairs from <paramref name="list"/>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="list"/> is <c>null</c>.</exception>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToFrozen), "David McCarter", "1/28/2026", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static FrozenDictionary<TKey, TValue> ToFrozen<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> list, IEqualityComparer<TKey>? comparer = null) where TKey : notnull
	{
		return FrozenDictionary.ToFrozenDictionary(list, comparer);
	}

	/// <summary>
	/// Converts a <see cref="IDictionary{TKey, TValue}" /> to a <see cref="FrozenDictionary{TKey, TValue}" />.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="list">The dictionary to convert.</param>
	/// <returns>A <see cref="FrozenDictionary{TKey, TValue}"/> containing all key/value pairs from <paramref name="list"/>.</returns>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Obsolete("Use ToFrozen() instead. This method will be removed at the end of 2026.")]
	[Information(nameof(ToFrozenDictionary), "David McCarter", "6/3/2024", UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available)]
	public static FrozenDictionary<TKey, TValue> ToFrozenDictionary<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> list) where TKey : notnull
	{
		return list.ToFrozen();
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}"/> to an <see cref="ImmutableDictionary{TKey, TValue}"/>.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The source dictionary to convert.</param>
	/// <param name="keyComparer">
	/// An optional <see cref="IEqualityComparer{T}"/> to use for key comparison.
	/// If <c>null</c>, <see cref="EqualityComparer{T}.Default"/> is used.
	/// </param>
	/// <returns>An immutable dictionary containing all key-value pairs from <paramref name="collection"/>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is <c>null</c>.</exception>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToImmutable), "David McCarter", "1/28/2026", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static ImmutableDictionary<TKey, TValue> ToImmutable<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, IEqualityComparer<TKey>? keyComparer = null) where TKey : notnull
	{
		return ImmutableDictionary.CreateRange(keyComparer, null, collection.ArgumentNotNull());
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}" /> to an <see cref="ImmutableDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to convert.</param>
	/// <returns>An <see cref="ImmutableDictionary{TKey, TValue}"/> containing all key/value pairs from <paramref name="collection"/>.</returns>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Obsolete("Use ToImmutable() instead. This method will be removed at the end of 2026.")]
	[Information(nameof(ToImmutableDictionary), "David McCarter", "11/21/2020", UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available)]
	public static ImmutableDictionary<TKey, TValue> ToImmutableDictionary<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection) where TKey : notnull
	{
		return [.. collection];
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}"/> to an <see cref="ImmutableSortedDictionary{TKey, TValue}"/>.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The source dictionary to convert.</param>
	/// <param name="keyComparer">
	/// An optional <see cref="IComparer{T}"/> to use for key ordering.
	/// If <c>null</c>, <see cref="Comparer{T}.Default"/> is used.
	/// </param>
	/// <returns>An immutable sorted dictionary containing all key-value pairs from <paramref name="collection"/>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is <c>null</c>.</exception>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToImmutableSorted), "David McCarter", "1/28/2026", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static ImmutableSortedDictionary<TKey, TValue> ToImmutableSorted<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, IComparer<TKey>? keyComparer = null) where TKey : notnull
	{
		return ImmutableSortedDictionary.CreateRange(keyComparer, null, collection.ArgumentNotNull());
	}

	/// <summary>
	/// Converts <see cref="IDictionary{TKey, TValue}" /> to <see cref="ImmutableSortedDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the t keyFunction.</typeparam>
	/// <typeparam name="TValue">The type of the t valueFunction.</typeparam>
	/// <param name="collection">The values.</param>
	/// <returns>ImmutableSortedDictionary&lt;TKey, TValue&gt;.</returns>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Obsolete("Use ToImmutableSorted() instead. This method will be removed at the end of 2026.")]
	[Information(nameof(ToImmutableSortedDictionary), "David McCarter", "7/3/2024", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static ImmutableSortedDictionary<TKey, TValue> ToImmutableSortedDictionary<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection) where TKey : notnull
	{
		return collection.ToImmutableSorted();
	}

	/// <summary>
	/// Creates a lookup function from the specified dictionary that returns the value for a given key,
	/// or a provided default value when the key is not present.
	/// </summary>
	/// <typeparam name="TKey">The type of the dictionary keys.</typeparam>
	/// <typeparam name="TValue">The type of the dictionary values.</typeparam>
	/// <param name="collection">The source dictionary used for lookups. Must not be null.</param>
	/// <param name="defaultValue">The value to return when a requested key is not found in the dictionary.</param>
	/// <returns>
	/// A <see cref="Func{T,TResult}"/> delegate that accepts a <typeparamref name="TKey"/> and returns the corresponding
	/// <typeparamref name="TValue"/> if present; otherwise, returns <paramref name="defaultValue"/>.
	/// </returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is null.</exception>
	/// <remarks>
	/// <para>
	/// The returned function performs O(1) average-time lookups using <see cref="IDictionary{TKey, TValue}.TryGetValue"/>.
	/// This is useful for scenarios where a default fallback value is desired without modifying the dictionary.
	/// </para>
	/// <para>
	/// If <paramref name="defaultValue"/> is a reference type and null is passed, the function will return null for missing keys.
	/// </para>
	/// </remarks>
	/// <example>
	/// <code>
	/// var dict = new Dictionary&lt;string, int&gt; { ["one"] = 1 };
	/// var lookup = dict.ToLookupWithDefault(0);
	///
	/// var a = lookup("one");   // returns 1
	/// var b = lookup("two");   // returns 0 (default)
	/// </code>
	/// </example>
	[Pure]
	[return: NotNull]
	[Information("Original code by Simon Painter.", author: "David McCarter", createdOn: "1/3/2025", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static Func<TKey, TValue> ToLookupWithDefault<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, TValue defaultValue)
	where TKey : notnull
	{
		collection = collection.ArgumentNotNull();

		return x => collection.TryGetValue(x, out var val) ? val : defaultValue;
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}"/> to a <see cref="ReadOnlyDictionary{TKey, TValue}"/>.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="dictionary">The source dictionary to wrap.</param>
	/// <returns>A read-only dictionary that wraps <paramref name="dictionary"/>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="dictionary"/> is null.</exception>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information(nameof(ToReadOnly), "David McCarter", "1/28/2026", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static ReadOnlyDictionary<TKey, TValue> ToReadOnly<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> dictionary) where TKey : notnull
	{
		return new(dictionary.ArgumentNotNull());
	}

	/// <summary>
	/// Converts to a <see cref="IDictionary{TKey, TValue}" /> to a <see cref="ReadOnlyCollection{KeyValuePair}" />.
	/// </summary>
	/// <typeparam name="TKey">The type of the keyFunction.</typeparam>
	/// <typeparam name="TValue">The type of the valueFunction.</typeparam>
	/// <param name="dictionary">The dictionary.</param>
	/// <returns>ReadOnlyCollection&lt;KeyValuePair&lt;TKey, TValue&gt;&gt;.</returns>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Obsolete("Use ToReadOnly() instead. Method will be removed at the end of 2026.")]
	[Information(nameof(ToReadOnlyCollection), "David McCarter", "11/6/2023", UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available)]
	public static ReadOnlyDictionary<TKey, TValue> ToReadOnlyCollection<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> dictionary) where TKey : notnull
	{
		return dictionary.ToReadOnly();
	}

	/// <summary>
	/// Converts <see cref="IDictionary{TKey, TValue}" /> to <see cref="ReadOnlyDictionary{TKey, TValue}" />.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to convert. Must not be null.</param>
	/// <returns>A <see cref="ReadOnlyDictionary{TKey, TValue}"/> that wraps the original dictionary.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is null.</exception>
	/// <remarks>
	/// <para>
	/// This method creates a read-only wrapper around an existing dictionary. The wrapper provides
	/// a read-only view of the underlying dictionary - modifications to the source dictionary will
	/// be visible through the read-only wrapper.
	/// </para>
	/// <para>
	/// <b>Performance Characteristics:</b>
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <description>
	/// <b>Wrapper pattern:</b> <see cref="ReadOnlyDictionary{TKey, TValue}"/> is a thin wrapper
	/// that does not copy elements. It provides O(1) construction time regardless of dictionary size.
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <b>No data duplication:</b> The wrapper references the original dictionary, so memory
	/// usage is minimal (just the wrapper object overhead, ~24-32 bytes).
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <b>Lookup performance:</b> All read operations (TryGetValue, ContainsKey, indexer) delegate
	/// directly to the underlying dictionary with O(1) complexity.
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <b>Live view:</b> Changes to the source dictionary are immediately visible through the
	/// read-only wrapper. This is different from immutable collections which create independent copies.
	/// </description>
	/// </item>
	/// </list>
	/// <para>
	/// <b>Comparison to Other Read-Only Collections:</b>
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <description>
	/// <see cref="ReadOnlyDictionary{TKey, TValue}"/> - Mutable source, read-only wrapper (this method)
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <see cref="IReadOnlyDictionary{TKey, TValue}"/> - Interface that provides read-only semantics
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <see cref="FrozenDictionary{TKey, TValue}"/> - Immutable, optimized for fast lookups (50-80% faster)
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <see cref="ImmutableDictionary{TKey, TValue}"/> - Fully immutable, copy-on-write semantics
	/// </description>
	/// </item>
	/// </list>
	/// <para>
	/// <b>When to Use Each Collection Type:</b>
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <description>
	/// <b>ReadOnlyDictionary:</b> When you need to expose a dictionary publicly but prevent modifications,
	/// while keeping the source mutable internally.
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <b>FrozenDictionary:</b> When the dictionary never changes after initialization and maximum
	/// lookup performance is critical (use <see cref="ToFrozenDictionary{TKey, TValue}"/> instead).
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <b>ImmutableDictionary:</b> When you need true immutability with structural sharing for
	/// efficient updates (use <see cref="ToImmutableDictionary{TKey, TValue}"/> instead).
	/// </description>
	/// </item>
	/// </list>
	/// <para>
	/// <b>Thread Safety:</b> <see cref="ReadOnlyDictionary{TKey, TValue}"/> itself is thread-safe
	/// for read operations. However, if the underlying dictionary is modified concurrently, you must
	/// provide external synchronization.
	/// </para>
	/// </remarks>
	/// <example>
	/// <code>
	/// var mutableDict = new Dictionary&lt;string, int&gt;
	/// {
	///     ["one"] = 1,
	///     ["two"] = 2
	/// };
	/// 
	/// // ToUniqueCollection read-only wrapper
	/// var readOnlyDict = mutableDict.ToReadOnlyDictionary();
	/// 
	/// // Reads work fine
	/// var value = readOnlyDict["one"]; // value = 1
	/// 
	/// // Modifications throw NotSupportedException
	/// // readOnlyDict["three"] = 3; // ❌ Throws at runtime
	/// 
	/// // Changes to source are visible
	/// mutableDict["three"] = 3;
	/// Console.WriteLine(readOnlyDict.Count); // Outputs: 3
	/// </code>
	/// </example>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Obsolete("Use ToReadOnly() instead. Method will be removed at the end of 2026.")]
	[Information(nameof(ToReadOnlyDictionary), "David McCarter", "6/3/2024", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static ReadOnlyDictionary<TKey, TValue> ToReadOnlyDictionary<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection) where TKey : notnull
	{
		return new(collection.ArgumentNotNull());
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}"/> to a <see cref="SortedDictionary{TKey, TValue}"/>.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The source dictionary to convert.</param>
	/// <returns>A sorted dictionary containing all key-value pairs from <paramref name="collection"/>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> is null.</exception>
	[Pure]
	[return: NotNull]
	[Information(nameof(ToSorted), "David McCarter", "1/28/2026", UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static SortedDictionary<TKey, TValue> ToSorted<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection) where TKey : notnull
	{
		return new(collection.ArgumentNotNull());
	}

	/// <summary>
	/// Converts an <see cref="IDictionary{TKey, TValue}"/> to a <see cref="SortedDictionary{TKey, TValue}"/> using the specified comparer.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The source dictionary to convert.</param>
	/// <param name="comparer">The comparer to use for sorting the keys.</param>
	/// <returns>A sorted dictionary containing all key-value pairs from <paramref name="collection"/>.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> or <paramref name="comparer"/> is null.</exception>
	[Pure]
	[return: NotNull]
	[Information(nameof(ToSorted), UnitTestStatus = UnitTestStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static SortedDictionary<TKey, TValue> ToSorted<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [DisallowNull] IComparer<TKey> comparer) where TKey : notnull
	{
		return new(collection.ArgumentNotNull(), comparer.ArgumentNotNull());
	}

	/// <summary>
	/// Converts a <see cref="IDictionary{TKey, TValue}" /> to a <see cref="SortedDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to convert.</param>
	/// <returns>A <see cref="SortedDictionary{TKey, TValue}"/> containing the elements from <paramref name="collection"/> in sorted key order.</returns>
	[Pure]
	[return: NotNull]
	[Obsolete("Use ToSorted() instead. This method will be removed at the end of 2026.")]
	[Information(nameof(ToSortedDictionary), "David McCarter", "6/27/2022", UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available)]
	public static SortedDictionary<TKey, TValue> ToSortedDictionary<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection) where TKey : notnull
	{
		return collection.ToSorted();
	}

	/// <summary>
	/// Converts a <see cref="IDictionary{TKey, TValue}" /> to a <see cref="SortedDictionary{TKey, TValue}" /> using the specified comparer.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to convert.</param>
	/// <param name="comparer">The comparer to use for sorting the keys.</param>
	/// <returns>A <see cref="SortedDictionary{TKey, TValue}" /> containing the elements from the original dictionary, sorted according to the specified comparer.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/> or <paramref name="comparer"/> is null.</exception>
	[Pure]
	[return: NotNull]
	[Obsolete("Use ToSorted() instead. This method will be removed at the end of 2026.")]
	[Information(nameof(ToSortedDictionary), UnitTestStatus = UnitTestStatus.Completed, Status = Status.Available)]
	public static SortedDictionary<TKey, TValue> ToSortedDictionary<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [DisallowNull] IComparer<TKey> comparer) where TKey : notnull
	{
		return collection.ToSorted(comparer);
	}

	/// <summary>
	/// Tries to get the value associated with the specified key. If the key does not exist, 
	/// uses the specified function to generate a value, which is then added to the dictionary.
	/// </summary>
	/// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
	/// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
	/// <param name="collection">The dictionary to search or add to.</param>
	/// <param name="key">The key of the value to get or add.</param>
	/// <param name="valueFunction">The function to generate a value if the key does not exist.</param>
	/// <returns>The value associated with the specified key, or the value generated by the function if the key does not exist.</returns>
	/// <exception cref="ArgumentNullException">Thrown if <paramref name="collection"/>, <paramref name="key"/>, or <paramref name="valueFunction"/> is null.</exception>
	/// <remarks>
	/// <para>
	/// This method provides a "get-or-compute-and-add" operation that retrieves an existing value 
	/// or computes and adds a new one. This is particularly useful for lazy initialization patterns.
	/// </para>
	/// <para>
	/// <b>Performance Optimization:</b> This method checks for the key's existence first using 
	/// <see cref="IDictionary{TKey, TValue}.TryGetValue"/>. The <paramref name="valueFunction"/> 
	/// is only invoked if the key doesn't exist, avoiding unnecessary computation. After computing 
	/// the value, it uses the dictionary indexer for the add operation, which is more efficient 
	/// than <c>Add</c> in this context.
	/// </para>
	/// <para>
	/// <b>Comparison to Similar Methods:</b>
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <description>
	/// <see cref="GetOrAdd{TKey, TValue}(IDictionary{TKey, TValue}, TKey, TValue)"/> - Takes a pre-computed value
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <see cref="TryGetValue{TKey, TValue}(IDictionary{TKey, TValue}, TKey, Func{TKey, TValue})"/> - 
	/// Lazy evaluation with a factory function (this method)
	/// </description>
	/// </item>
	/// <item>
	/// <description>
	/// <see cref="ConcurrentDictionary{TKey, TValue}.GetOrAdd(TKey, Func{TKey, TValue})"/> - 
	/// Thread-safe version for concurrent scenarios
	/// </description>
	/// </item>
	/// </list>
	/// <para>
	/// <b>Thread Safety:</b> This method is not thread-safe. Use appropriate synchronization 
	/// if calling from multiple threads, or use <see cref="ConcurrentDictionary{TKey, TValue}"/> instead.
	/// </para>
	/// </remarks>
	/// <example>
	/// <code>
	/// var cache = new Dictionary&lt;string, ExpensiveObject&gt;();
	/// 
	/// // Factory function is only called if key doesn't exist
	/// var obj = cache.TryGetValue("key1", key => new ExpensiveObject(key));
	/// 
	/// // Second call returns cached instance without calling the factory
	/// var sameObj = cache.TryGetValue("key1", key => new ExpensiveObject(key)); // obj == sameObj
	/// </code>
	/// </example>
	[Pure]
	[return: NotNull]
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	[Information("Original code by Simon Painter.", author: "David McCarter", createdOn: "1/3/2025", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static TValue TryGetValue<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [DisallowNull] TKey key, [DisallowNull] Func<TKey, TValue> valueFunction)
	where TKey : notnull
	where TValue : notnull
	{
		// Validate all arguments upfront - this is more efficient than validating valueFunction conditionally
		collection = collection.ArgumentNotNull();
		key = key.ArgumentNotNull();
		valueFunction = valueFunction.ArgumentNotNull();

		// Fast path: if key exists, return value immediately
		if (collection.TryGetValue(key, out var value))
		{
			return value;
		}

		// Key doesn't exist, compute and add new value
		var newValue = valueFunction(key);
		collection[key] = newValue; // Use indexer which is faster than Add for this scenario

		return newValue;
	}

	/// <summary>
	/// Upserts the specified item into the <see cref="IDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" /> and <paramref name="item" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <param name="collection">The dictionary.</param>
	/// <param name="item">The item.</param>
	/// <remarks>
	/// This method uses direct dictionary indexer assignment which performs a single O(1) operation
	/// instead of the previous ContainsKey + Remove + Add pattern which required three O(1) operations.
	/// The indexer automatically handles both insert and update scenarios efficiently in .NET 10.
	/// </remarks>
	[Information(nameof(Upsert), "David McCarter", "5/2/2021", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static void Upsert<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [AllowNull] in TValue item) where TValue : IDataModel<TValue, TKey> where TKey : notnull
	{
		if (item is null)
		{
			return;
		}

		collection = collection.ArgumentNotNull();

		collection[item.Id] = item;
	}

	/// <summary>
	/// Inserts or updates the item into a <see cref="IDictionary{TKey, TValue}" />.
	/// Validates that <paramref name="collection" />, <paramref name="key" /> and
	/// <paramref name="item" /> is not null.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <param name="collection">The dictionary.</param>
	/// <param name="key">The key.</param>
	/// <param name="item">The value.</param>
	/// <remarks>
	/// This method uses direct dictionary indexer assignment which performs a single O(1) operation
	/// instead of the previous ContainsKey + Remove + Add pattern which required three O(1) operations.
	/// The indexer automatically handles both insert and update scenarios efficiently in .NET 10.
	/// </remarks>
	[Information(nameof(Upsert), author: "David McCarter", createdOn: "7/15/2020", UnitTestStatus = UnitTestStatus.Completed, OptimizationStatus = OptimizationStatus.Completed, BenchmarkStatus = BenchmarkStatus.Completed, Status = Status.Available)]
	public static void Upsert<TKey, TValue>([DisallowNull] this IDictionary<TKey, TValue> collection, [DisallowNull] TKey key, [AllowNull] in TValue item)
	{
		if (item is null)
		{
			return;
		}

		key = key.ArgumentNotNull();
		collection = collection.ArgumentNotNull();

		collection[key] = item;
	}
}
