<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<AnalysisLevel>none</AnalysisLevel>
	<AssemblyVersion>2025.8.5.1</AssemblyVersion>
	<BaseOutputPath>..\..\..\AppBin</BaseOutputPath>
	<EnableNETAnalyzers>false</EnableNETAnalyzers>
	<FileVersion>2025.8.5.1</FileVersion>
	<IsPackable>false</IsPackable>
	<NeutralLanguage>en-US</NeutralLanguage>
	<RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
	<RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
	<TargetFramework>net10.0</TargetFramework>
	<Version>2025.8.5.1</Version>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<OutputPath>..\..\..\AppBin</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<OutputPath>..\..\..\AppBin</OutputPath>
  </PropertyGroup>

  <ItemGroup>
	<Compile Remove="IEasyDisposableTests.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
	<PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
	<PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
	<PackageReference Include="coverlet.collector" Version="6.0.4">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\dotNetTips.Spargine.10.Core\dotNetTips.Spargine.10.Core.csproj" />
	<ProjectReference Include="..\..\dotNetTips.Spargine.10.Extensions\dotNetTips.Spargine.10.Extensions.csproj" />
	<ProjectReference Include="..\..\dotNetTips.Spargine.10.Tester\dotNetTips.Spargine.10.Tester.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Compile Update="Properties\Resources.Designer.cs">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Resources.resx</DependentUpon>
	</Compile>
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Update="Properties\Resources.resx">
	  <Generator>ResXFileCodeGenerator</Generator>
	  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	</EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\david\.nuget\packages\mstest.testadapter\4.0.2\buildTransitive\net9.0\\Microsoft.TestPlatform.AdapterUtilities.dll" />
  </ItemGroup>

</Project>
