//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTips.Spargine.Tester.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetTips.Spargine.Tester.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;addresses&quot;:[{&quot;address1&quot;:&quot;06333 nimmmrkggrtbkbomycw&quot;,&quot;address2&quot;:&quot;ngcwwwnjkcvtlllgcup 83466&quot;,&quot;city&quot;:&quot;\u00C1ngeles&quot;,&quot;country&quot;:&quot;Costa Rica&quot;,&quot;countryProvince&quot;:&quot;hecyxpupsbdyoqrtiovw&quot;,&quot;id&quot;:&quot;6d5c08f77ffa4f3fbcbcbe46bdf4b19f&quot;,&quot;phone&quot;:&quot;17811851&quot;,&quot;postalCode&quot;:&quot;40688&quot;,&quot;state&quot;:&quot;Heredia Province&quot;},{&quot;address1&quot;:&quot;51055 ayncmjrvvcqowfnfqek&quot;,&quot;address2&quot;:&quot;ecobmtuamlkrlcanmws 06508&quot;,&quot;city&quot;:&quot;San Ram\u00F3n&quot;,&quot;country&quot;:&quot;Costa Rica&quot;,&quot;countryProvince&quot;:&quot;bcgftqgbynsedgspwmjn&quot;,&quot;id&quot;:&quot;b2475b3505454f558991332d634677be&quot;,&quot;phone&quot;:&quot;26522757 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PeopleJson {
            get {
                return ResourceManager.GetString("PeopleJson", resourceCulture);
            }
        }
    }
}
