<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
	<AnalysisLevel>latest-recommended</AnalysisLevel>
	<AnalysisMode>AllEnabledByDefault</AnalysisMode>
	<ApplicationIcon>SPARGINE-ICON-GRAPHIC-SMALL.ico</ApplicationIcon>
	<AssemblyName>$(MSBuildProjectName)</AssemblyName>
	<AssemblyVersion>2025.10.12.29</AssemblyVersion>
	<Authors>David McCarter</Authors>
	<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
	<AutoIncrementPackageRevision>true</AutoIncrementPackageRevision>
	<BaseOutputPath>..\..\AppBin</BaseOutputPath>
	<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
	<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
	<Company>dotNetTips.com - McCarter Consulting</Company>
	<Configurations>Debug;Release</Configurations>
	<Copyright>McCarter Consulting (David McCarter)</Copyright>
	<DebugSymbols>true</DebugSymbols>
	<DebugType>portable</DebugType>
	<Description>Common code to help with unit tests by generating random data.</Description>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
	<EnableNETAnalyzers>true</EnableNETAnalyzers>
	<EnablePackageValidation>false</EnablePackageValidation>
	<EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	<FileVersion>2025.10.12.29</FileVersion>
	<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	<GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>
	<ImplicitUsings>enable</ImplicitUsings>
	<IncludeSymbols>true</IncludeSymbols>
	<LangVersion>latest</LangVersion>
	<NeutralLanguage>en-US</NeutralLanguage>
	<Nullable>enable</Nullable>
	<PackageIcon>SPARGINE-ICON-GRAPHIC-SMALL.png</PackageIcon>
	<PackageProjectUrl>https://github.com/RealDotNetDave/DotNetTips.Spargine.8</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	<PackageTags>David McCarter, dotNetDave, dotNetTips.com, Spargine</PackageTags>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/RealDotNetDave/DotNetTips.Spargine.8</RepositoryUrl>
	<RootNamespace>DotNetTips.Spargine.Tester</RootNamespace>
	<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
	<RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
	<SelfContained>true</SelfContained>
	<ServerGarbageCollection>true</ServerGarbageCollection>
	<SignAssembly>false</SignAssembly>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<TargetFramework>net10.0</TargetFramework>
	<Title>DotNetTips.Spargine.10.Tester</Title>
	<Version>2025.10.12.29</Version>
  </PropertyGroup>

  <PropertyGroup>
	<NuGetAudit>true</NuGetAudit>
	<NuGetAuditMode>all</NuGetAuditMode>
	<NuGetAuditLevel>low</NuGetAuditLevel>
	<WarningsAsErrors Condition="$(ContinuousIntegrationBuild) == 'true' OR '$(Configuration)' == 'Release'">
	  (WarningsAsErrors);NU1900;NU1901;NU1902;NU1903;NU1904
	</WarningsAsErrors>
	<PackageReleaseNotes>--JAN 2026: Initial .NET 10 release.</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<DocumentationFile>..\..\AppBin\dotNetTips.Spargine.10.Tester.xml</DocumentationFile>
	<OutputPath>..\..\AppBin\</OutputPath>
	<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsAsErrors />
	<DebugType>portable</DebugType>
  </PropertyGroup>


  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<OutputPath>..\..\AppBin\</OutputPath>
	<DocumentationFile>..\..\AppBin\DotNetTips.Spargine.Tester.xml</DocumentationFile>
	<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsAsErrors />
	<DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
	<None Include="..\..\README.md">
	  <Pack>true</Pack>
	  <PackagePath>\</PackagePath>
	</None>
  </ItemGroup>

  <ItemGroup>
	<Content Include="SPARGINE-ICON-GRAPHIC-SMALL.ico" />
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Include="SPARGINE-ICON-GRAPHIC-SMALL.png">
	  <Pack>true</Pack>
	  <PackagePath>\</PackagePath>
	  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	</EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
	<Compile Remove="Collections\**" />
	<EmbeddedResource Remove="Collections\**" />
	<None Remove="Collections\**" />
  </ItemGroup>

  <ItemGroup>
	<Compile Remove="Extensions\PersonRecordExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
	<None Remove="dotNetTips.Spargine.Tester.xml" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="IDisposableAnalyzers" Version="4.0.8">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="4.14.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\dotNetTips.Spargine.10.Core\DotNetTips.Spargine.10.Core.csproj" />
	<ProjectReference Include="..\dotNetTips.Spargine.10.Extensions\DotNetTips.Spargine.10.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Compile Update="Properties\Resources.Designer.cs">
	  <DesignTime>true</DesignTime>
	  <AutoGen>true</AutoGen>
	  <DependentUpon>Resources.resx</DependentUpon>
	</Compile>
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Update="Properties\Resources.resx">
	  <Generator>ResXFileCodeGenerator</Generator>
	  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	</EmbeddedResource>
  </ItemGroup>

</Project>
